services:
  # ---- BACKEND: Spring Boot (Docker) ----
  - type: web
    name: pesekatesh-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: ALLOWED_ORIGINS
        value: "*"   # rregulloje me URL-në e frontend-it (Netlify) pas deploy të parë
